"""Hierarchical qubit-correlation analysis of quantum_radio's 12-qubit hardware/
simulator run.

This is a repurposing, not a native feature of the golden-ratio phase-kick
circuit quantum_radio.py runs: that circuit has no encoding/ancilla structure,
so the "qubits 0-5 vs 6-11" split drawn throughout the plots below is an
arbitrary bipartition used to demonstrate a hierarchical-analysis methodology,
not a genuine encoding subspace. Treat the highlighting as "here's where we cut
the register in half," not "here's where the meaningful physics lives."

The statistical core (marginals, correlation, bias-corrected/null-calibrated
mutual information, plotting) lives in ../qubit_hierarchy_core.py, shared with
quantum_prime_gaps/qubit_hierarchy_analysis.py -- this script owns only data
loading and the report narrative specific to this dataset.

Reads quantum_radio_results_12q.json (bitstring -> shot count, for both the
ibm_marrakesh hardware run and the AerSimulator control) and produces:

1. Per-qubit marginals P(qubit_i = |1>), hardware vs simulator.
2. A 12x12 pairwise correlation matrix (Pearson, over the binary per-qubit
   outcome), hardware vs simulator vs their difference.
3. A hierarchical partition tree: qubits recursively bisected in index order
   (0-5 | 6-11, then 0-2 | 3-5, etc.), with mutual information between each
   node's two halves as the edge weight -- drawn as a dendrogram.
4. A 2-sigma flag on any qubit pair where the hardware correlation diverges
   from the simulator correlation beyond sampling noise -- crosstalk or
   entanglement, this analysis alone can't tell which.

Run: .venv/bin/python quantum_radio/qubit_hierarchy_analysis.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent))
import qubit_hierarchy_core as core  # noqa: E402

HERE = Path(__file__).parent
RESULTS_PATH = HERE / "quantum_radio_results_12q.json"
SCREENSHOTS_DIR = HERE / "screenshots"
REPORT_PATH = HERE / "qubit_hierarchy_report.md"

N_QUBITS = 12
SPLIT_AT = 6  # the arbitrary "left half / right half" bipartition, qubits 0-5 vs 6-11
HW_LABEL = "Hardware (ibm_marrakesh)"


def load_counts() -> tuple[dict[str, int], dict[str, int]]:
    data = json.loads(RESULTS_PATH.read_text())
    assert data["n_qubits"] == N_QUBITS, f"expected a {N_QUBITS}-qubit run, got {data['n_qubits']}"
    return data["simulator_counts"], data["hardware_counts"]


def write_report(
    sim_p1: np.ndarray,
    hw_p1: np.ndarray,
    flagged: list[tuple[int, int, float, float, float]],
    threshold: float,
    marginals_path: Path,
    correlations_path: Path,
    dendrogram_path: Path,
    sim_tree: dict,
    hw_tree: dict,
    significant: list[str],
) -> None:
    lines = [
        "# Hierarchical qubit analysis -- quantum_radio 12-qubit run",
        "",
        "Repurposes quantum_radio's 12-qubit hardware (ibm_marrakesh) vs. AerSimulator",
        "counts to demonstrate a hierarchical qubit-correlation methodology. **The",
        "qubits 0-5 | 6-11 split is an arbitrary bipartition, not a genuine encoding/",
        "ancilla subspace** -- the golden-ratio phase-kick circuit this data comes from",
        "has no such structure. Whether any flagged pair below is crosstalk noise or",
        "something more structured isn't answerable from this data alone.",
        "",
        f"Generated by `qubit_hierarchy_analysis.py`. Source: `{RESULTS_PATH.name}`.",
        "",
        "## Marginals",
        "",
        f"![marginals]({marginals_path.relative_to(HERE)})",
        "",
        "| Qubit | P(=1) sim | P(=1) hw | Δ |",
        "|---|---:|---:|---:|",
    ]
    for i in range(N_QUBITS):
        lines.append(f"| q{i} | {sim_p1[i]:.4f} | {hw_p1[i]:.4f} | {hw_p1[i] - sim_p1[i]:+.4f} |")

    lines += [
        "",
        "## Pairwise correlations",
        "",
        f"![correlations]({correlations_path.relative_to(HERE)})",
        "",
        "## Hierarchical partition tree",
        "",
        "Edge weights are Miller-Madow bias-corrected mutual information (bits) between",
        "each node's two halves, then calibrated against a *simulated independence null*:",
        "200 synthetic datasets per node, drawn from independent Bernoulli qubits with that",
        "node's own observed marginals and shot count, giving a z-score for \"is this MI",
        "bigger than independent qubits would produce by chance.\" That second step matters",
        "-- the uncorrected plug-in estimator alone is a trap at the root: the full 12-qubit",
        "joint has 4096 possible outcomes from only 8192 shots (N/K ~ 2), which produces ~0.3",
        "bits of spurious \"structure\" on its own (naive root MI came out ~0.4 bits). Miller-",
        "Madow correction brings that down to ~0.11 bits -- still, on its own, looking like",
        "the biggest number in the tree by 20x. Only the null comparison resolves it: simulated",
        "independent qubits with the *same* marginals and shot count produce MI in the same",
        "~0.10 bit range purely from sampling noise, so the corrected root MI",
        f"(simulator={sim_tree['mi']:.4f} bits, z={sim_tree['z']:.2f}; hardware={hw_tree['mi']:.4f} bits,",
        f"z={hw_tree['z']:.2f}) is not distinguishable from noise. A node is only flagged",
        "significant (marked `*` in the figure) at z > 2.",
        "",
        f"![dendrogram]({dendrogram_path.relative_to(HERE)})",
        "",
        "**Partition-tree nodes exceeding z > 2 (simulator or hardware):**",
        "",
    ]
    if not significant:
        lines.append(
            "None. No qubit grouping at any level of the hierarchy -- including the top-level "
            "0-5 | 6-11 split -- shows more mutual information than independent qubits with the "
            "same marginals would produce by chance. Combined with the near-zero pairwise "
            "correlation matrix, there's no evidence of structure here at any granularity: "
            "\"noisy neighbors,\" not entanglement -- at least not at the level this circuit's "
            "measurement statistics can resolve it."
        )
    else:
        lines.extend(f"- {line}" for line in significant)
    lines += [
        "",
        "## Qubit pairs flagged beyond 2σ",
        "",
        f"2σ threshold on |hw correlation - sim correlation|, from the {8192}-shot sampling",
        f"noise on each Pearson estimate (see docstring for the approximation): **{threshold:.4f}**.",
        "",
    ]
    if not flagged:
        lines.append("None -- every pairwise correlation's hardware/simulator difference is within sampling noise.")
    else:
        lines.append("| Pair | Crosses 0-5|6-11? | sim corr | hw corr | Δ |")
        lines.append("|---|---|---:|---:|---:|")
        for i, j, sc, hc, delta in flagged:
            crosses = "yes" if (i < SPLIT_AT) != (j < SPLIT_AT) else "no"
            lines.append(f"| q{i}-q{j} | {crosses} | {sc:+.4f} | {hc:+.4f} | {delta:+.4f} |")
    lines.append("")

    REPORT_PATH.write_text("\n".join(lines))


def main() -> None:
    sim_counts, hw_counts = load_counts()
    sim_bits, sim_probs = core.counts_to_bits_and_probs(sim_counts, N_QUBITS)
    hw_bits, hw_probs = core.counts_to_bits_and_probs(hw_counts, N_QUBITS)

    sim_p1 = core.marginals(sim_bits, sim_probs)
    hw_p1 = core.marginals(hw_bits, hw_probs)
    marginals_path = core.plot_marginals(
        sim_p1,
        hw_p1,
        N_QUBITS,
        SCREENSHOTS_DIR / "qubit_hierarchy_marginals.png",
        highlight_upto=SPLIT_AT,
        hw_label=HW_LABEL,
        title_note="\n(shaded: qubits 0-5, the arbitrary left/right split used below)",
    )

    sim_corr = core.correlation_matrix(sim_bits, sim_probs)
    hw_corr = core.correlation_matrix(hw_bits, hw_probs)
    n_shots = 8192
    flagged = core.flag_divergent_pairs(sim_corr, hw_corr, n_shots, N_QUBITS)
    threshold = 2 * np.sqrt(2.0 / (n_shots - 3))
    correlations_path = core.plot_correlations(
        sim_corr,
        hw_corr,
        [(i, j) for i, j, *_ in flagged],
        N_QUBITS,
        SCREENSHOTS_DIR / "qubit_hierarchy_correlations.png",
        highlight_upto=SPLIT_AT,
        hw_label=HW_LABEL,
        split_label="0-5 | 6-11",
    )

    rng = np.random.default_rng(0)
    sim_tree = core.build_partition_tree(sim_bits, sim_probs, list(range(N_QUBITS)), n_shots, sim_p1, rng)
    hw_tree = core.build_partition_tree(hw_bits, hw_probs, list(range(N_QUBITS)), n_shots, hw_p1, rng)
    dendrogram_path = core.plot_dendrograms(
        sim_tree,
        hw_tree,
        N_QUBITS,
        SCREENSHOTS_DIR / "qubit_hierarchy_dendrogram.png",
        highlight_upto=SPLIT_AT,
        hw_label=HW_LABEL,
        title_note=" Shaded: qubits 0-5.",
    )

    sig: list[str] = []
    core.significant_nodes(sim_tree, "simulator", sig)
    core.significant_nodes(hw_tree, "hardware", sig)

    write_report(
        sim_p1,
        hw_p1,
        flagged,
        threshold,
        marginals_path,
        correlations_path,
        dendrogram_path,
        sim_tree,
        hw_tree,
        sig,
    )

    print(
        f"Root-level MI (qubits 0-5 vs 6-11): simulator={sim_tree['mi']:.4f} bits (z={sim_tree['z']:.2f}), "
        f"hardware={hw_tree['mi']:.4f} bits (z={hw_tree['z']:.2f})"
    )
    print(f"2-sigma correlation-divergence threshold: {threshold:.4f}")
    print(f"Flagged pairs: {len(flagged)} / {N_QUBITS * (N_QUBITS - 1) // 2}")
    for i, j, sc, hc, delta in flagged:
        crosses = "crosses 0-5|6-11" if (i < SPLIT_AT) != (j < SPLIT_AT) else "within one half"
        print(f"  q{i}-q{j} ({crosses}): sim={sc:+.4f} hw={hc:+.4f} delta={delta:+.4f}")
    print(f"Partition-tree nodes exceeding the z>2 independence-null significance bar: {len(sig)}")
    for line in sig:
        print(f"  {line}")
    print(f"\nWrote {marginals_path}, {correlations_path}, {dendrogram_path}, {REPORT_PATH}")


if __name__ == "__main__":
    main()
